# Generated by Django 4.1.7 on 2023-08-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
