# Generated by Django 4.1.5 on 2023-02-01 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('caption', models.TextField()),
                ('slug', models.SlugField(max_length=250)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], max_length=10)),
                ('preview_image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[825, 465], upload_to='VideoFiles/preview_image')),
                ('video_time', models.TimeField(null=True)),
                ('video_level', models.CharField(choices=[('preliminary', 'مقدماتی'), ('mean', 'متوسط'), ('advanced', 'پیشرفته')], default='mean', max_length=15)),
                ('price', models.PositiveIntegerField(default=0)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_teacher', to=settings.AUTH_USER_MODEL)),
                ('users_like', models.ManyToManyField(blank=True, related_name='videos_liked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'videoinformation',
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videofile', models.FileField(blank=True, null=True, upload_to='VideoFiles/videos')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('video_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_file', to='video.videoinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('activ', models.BooleanField(default=False)),
                ('video_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_cm', to='video.videoinformation')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
