# Generated by Django 4.2.4 on 2023-11-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_post_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_saves',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
