# Generated by Django 4.2.4 on 2023-11-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='نام'),
        ),
    ]
