# Generated by Django 4.2.4 on 2023-11-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_alter_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
    ]
