# Generated by Django 5.0 on 2024-02-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_name_order_firs_name_order_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
